# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = " "
  url = "#about"
  weight = 10

[[main]]
  name = "Research"
  url = "#research"
  weight = 21

  [[main]]
  name = "Publications"
  url = "#publications"
  weight = 31

[[main]]
  name = "Education"
  url = "#education"
  weight = 41

[[main]]
  name = "Awards"
  url = "#accomplishments"
  weight = 51

[[main]]
  name = "Mentoring"
  url = "#advisoring"
  weight = 61

[[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 71

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 81

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
    name = "Resume"
    url = "files/YayunDu_Resume.pdf"
    weight = 91

[[main]]
  name = "中文"
  url = "/zh/"
  weight = 99